import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed': '#ffe08e',
        'border-subtle': '#E8ECF0',
        'secondary': '#566065',
        'surface-bright': '#f6fafe',
        'surface-variant': '#dfe3e7',
        'admin-bg': '#0D1120',
        'on-primary-fixed-variant': '#3a3f8a',
        'inverse-primary': '#bfc2ff',
        'outline': '#777682',
        'secondary-container': '#dae4ea',
        'tertiary': '#755b00',
        'on-error': '#ffffff',
        'sidebar-active-light': '#ECEFFE',
        'on-surface': '#171c1f',
        'surface-tint': '#5257a3',
        'on-primary-fixed': '#090c5e',
        'surface-container-highest': '#dfe3e7',
        'table-hover': '#F5F7FF',
        'primary-fixed': '#e0e0ff',
        'error': '#C0392B',
        'inverse-surface': '#2c3134',
        'admin-accent': '#4A6CF7',
        'outline-variant': '#c7c5d2',
        'primary-fixed-dim': '#bfc2ff',
        'on-surface-variant': '#464651',
        'on-primary-container': '#858ada',
        'primary': '#020259',
        'tertiary-fixed-dim': '#ecc246',
        'on-error-container': '#93000a',
        'on-background': '#171c1f',
        'tertiary-container': '#cea62c',
        'on-tertiary-container': '#4f3d00',
        'on-secondary-fixed': '#131d21',
        'error-container': '#ffdad6',
        'on-tertiary-fixed-variant': '#584400',
        'primary-container': '#1b1f6b',
        'secondary-fixed-dim': '#bec8ce',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed': '#241a00',
        'success': '#1E8449',
        'surface-container': '#eaeef2',
        'on-secondary-fixed-variant': '#3f484d',
        'inverse-on-surface': '#edf1f5',
        'on-primary': '#ffffff',
        'surface': '#f6fafe',
        'on-secondary-container': '#5c666b',
        'surface-container-low': '#f0f4f8',
        'background': '#f6fafe',
        'on-tertiary': '#ffffff',
        'sidebar-light': '#F8F9FE',
        'secondary-fixed': '#dae4ea',
        'surface-dim': '#d6dade',
        'surface-container-high': '#e4e9ed',
        'on-secondary': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'topnav-height': '64px',
        'gutter': '24px',
        'page-padding': '32px',
        'card-padding': '20px',
        'sidebar-width': '240px',
        'input-height': '44px',
      },
      fontFamily: {
        'sidebar-label': ['Inter', 'sans-serif'],
        'page-title': ['Inter', 'sans-serif'],
        'nav-link': ['Inter', 'sans-serif'],
        'metric-value': ['Syne', 'sans-serif'],
        'section-title': ['Inter', 'sans-serif'],
        'table-header': ['Inter', 'sans-serif'],
        'table-cell': ['Inter', 'sans-serif'],
        'badge': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'sidebar-label': ['13px', { lineHeight: '18px', fontWeight: '500' }],
        'page-title': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'page-title-mobile': ['22px', { lineHeight: '28px', fontWeight: '700' }],
        'table-header': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'table-cell': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'nav-link': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'metric-value': ['36px', { lineHeight: '44px', fontWeight: '700' }],
        'section-title': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'badge': ['11px', { lineHeight: '14px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};

export default config;
